### ISSUE TITLE
Spawn Locations

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/balance-screen#4]
A. Make each side have to turn 90 degrees, rather than one side turning 180 degrees.
B. Spread out the spawn positions further? Prolly not needed after A. Its also better not to spread them out too far, or faster units get the the battle before slower units. Rather have all units engage at about the same time. The longest weapon range 6-7k I think, and I'm guessing spawn locations are already a bit further than that.

**Comment by Novaras** [comment]
4590cd7a8a60b6e5a25855fe3bda1a6f4c620368
